#!/usr/bin/env ansible-playbook
---
- hosts: development
  tasks:
    - name: Include vars
      include_vars:
        file: vars.yml

    - include_role:
        name: prepd/yadr

    - include_role:
        name: prepd/credentials
      vars:
        credentials_src_dirs: credentials
