#!/usr/bin/env ansible-playbook
# NOTE: This playbook installs and configures a docker swarm cluster on Vagrant hosts
# TODO: Remove machine_env from project group_vars
# TODO: If abstract the IP addresses from here then can run in other environments
---
- hosts: master

  pre_tasks:
    - include_vars: '{{ item }}'
      with_first_found:
         - '../../developer.yml'
         - '~/.ansible-developer.yml'

  roles:
    - { role: docker, login: yes }

  tasks:
    - name: insert ssh aliases for each node
      blockinfile:
        create: yes
        dest: ~/.zsh.after/aliases.zsh
        marker: '# {mark} ANSIBLE MANAGED BLOCK (cluster.yml)'
        block: |
          alias n1='ssh node1.local'
          alias n2='ssh node2.local'
          alias n3='ssh node3.local'


# Update configration only on the worker nodes
- hosts: nodes

  roles:
    - common
    - docker


# Update configuration on every node (worker nodes, inculding master; aka cluster)
- hosts: cluster
  become: yes

  tasks:
    - name: Add mappings to /etc/hosts
      blockinfile:
        dest: /etc/hosts
        marker: '# {mark} ANSIBLE MANAGED BLOCK (cluster.yml)'
        block: |
          10.100.199.200 node0.local
          10.100.199.201 node1.local
          10.100.199.202 node2.local
          10.100.199.203 node3.local
