#!/usr/bin/env ansible-playbook
# NOTE: This playbook installs all the application dependenices for development
# on the 'dev' machine so it is a stand-alone product
---
- hosts: dev
  become: yes

  roles:
    - common
    - postgres
    - redis
    # - rabbitmq


- hosts: dev

  pre_tasks:
    - include_vars: '{{ item }}'
      with_first_found:
         - '../../developer.yml'
         - '~/.ansible-developer.yml'

  roles:
    - yadr
    - developer
    - developer-tools

  tasks:
    - debug: var=database_password
      tags: [ding]
    - debug: var=database_username
      tags: [ding]
    - debug: var=database_host
      tags: [ding]
    - debug: var=ansible_env.USER
      tags: [ding]
    - debug: var=app
      tags: [ding]
